services:
  app-backend:
    build: .
    restart: always
    tty: true
    working_dir: /var/www/application
    env_file:
      - .env
    volumes:
      - .:/var/www/application
    container_name: app-backend

  app-nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: always
    tty: true
    environment:
      - "APPLICATION_UPSTREAM=app-backend:9000"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./public/:/var/www/application/public/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app-backend

  app-mysql:
    image: library/mysql:8.0
    container_name: application-mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 111111
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_NAME: mysql
    volumes:
      - applicationMysqlData:/var/lib/mysql
      - applicationMysqlFiles:/var/lib/mysql-files

volumes:
  applicationMysqlData:
  applicationMysqlFiles:
